// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Entities.Common;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities.Models;

public partial class Customer : BaseEntity
{
    [Key]
    public Guid id { get; set; }

    [Required]
    public string name { get; set; }

    public DateTime createdate { get; set; }

    public DateTime updatedate { get; set; }

    public DateTime deletedate { get; set; }

    [InverseProperty("customerid_fororderNavigation")]
    public virtual ICollection<Order> Order { get; set; } = new List<Order>();
}