// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Entities.Common;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities.Models;

public partial class Order : BaseEntity
{
    [Key]
    public Guid id { get; set; }

    [Required]
    public string description { get; set; }

    [Required]
    public string address { get; set; }

    public DateTime createdate { get; set; }

    public DateTime updatedate { get; set; }

    public DateTime deletedate { get; set; }

    public Guid customerid_fororder { get; set; }

    public Guid productid_fororder { get; set; }

    [ForeignKey("customerid_fororder")]
    [InverseProperty("Order")]
    public virtual Customer customerid_fororderNavigation { get; set; }

    [ForeignKey("productid_fororder")]
    [InverseProperty("Order")]
    public virtual Product productid_fororderNavigation { get; set; }
}