// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Entities.Common;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities.Models;

public partial class Order : BaseEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    public string Address { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public DateTime DeleteDate { get; set; }

    public int CustomerId_forOrder { get; set; }

    public int ProductId_forOrder { get; set; }

    [ForeignKey("CustomerId_forOrder")]
    [InverseProperty("Order")]
    public virtual Customer CustomerId_forOrderNavigation { get; set; }

    [ForeignKey("ProductId_forOrder")]
    [InverseProperty("Order")]
    public virtual Product ProductId_forOrderNavigation { get; set; }
}